<#
.SYNOPSIS
  Initializes Environment.props by detecting Steam and mod manager paths.
.DESCRIPTION
  Searches for common Steam library folders and active r2modman profiles,
  then generates a localized Environment.props from Environment.props.example.
.PARAMETER ProjectPath
  Path to the mod project directory (defaults to current directory).
.PARAMETER Force
  Overwrites existing Environment.props if specified.
#>

[CmdletBinding()]
param (
    [string]$ProjectPath = (Get-Location).Path,
    [switch]$Force
)

$targetProps = Join-Path $ProjectPath "Environment.props"

if ((Test-Path $targetProps) -and -not $Force) {
    Write-Warning "Environment.props already exists at '$targetProps'. Use -Force to overwrite."
    return
}

# 1. Detect Valheim installation path
$detectedValheim = $null
$candidatePaths = @(
    "C:\Program Files (x86)\Steam\steamapps\common\Valheim",
    "D:\SteamLibrary\steamapps\common\Valheim",
    "D:\Games\SteamLibrary\steamapps\common\Valheim",
    "E:\SteamLibrary\steamapps\common\Valheim",
    "F:\SteamLibrary\steamapps\common\Valheim"
)

# Also check Steam registry key if on Windows
if ($IsWindows -or $env:OS -match "Windows") {
    try {
        $steamPath = (Get-ItemProperty -Path "HKCU:\Software\Valve\Steam" -Name "SteamPath" -ErrorAction SilentlyContinue).SteamPath
        if ($steamPath) {
            $regCandidate = Join-Path $steamPath "steamapps\common\Valheim"
            $candidatePaths = @($regCandidate) + $candidatePaths
        }
    } catch {}
}

foreach ($cand in $candidatePaths) {
    if (Test-Path (Join-Path $cand "valheim.exe")) {
        $detectedValheim = $cand
        break
    }
}

if (-not $detectedValheim) {
    $detectedValheim = "C:\Program Files (x86)\Steam\steamapps\common\Valheim"
    Write-Host "Valheim path not auto-detected; using default: $detectedValheim" -ForegroundColor Yellow
} else {
    Write-Host "Auto-detected Valheim at: $detectedValheim" -ForegroundColor Green
}

# 2. Detect r2modman profile
$detectedR2 = $null
$r2ProfilesRoot = "$env:APPDATA\r2modmanPlus-local\Valheim\profiles"
if (Test-Path $r2ProfilesRoot) {
    $profiles = Get-ChildItem -Path $r2ProfilesRoot -Directory | Select-Object -ExpandProperty Name
    if ($profiles.Count -gt 0) {
        $selectedProfile = $profiles[0]
        $detectedR2 = "`$(AppData)\r2modmanPlus-local\Valheim\profiles\$selectedProfile"
        Write-Host "Auto-detected r2modman profile: $detectedR2" -ForegroundColor Green
    }
}

if (-not $detectedR2) {
    $detectedR2 = "`$(AppData)\r2modmanPlus-local\Valheim\profiles\Default"
}

# 3. Generate Environment.props content
$xmlContent = @"
<?xml version="1.0" encoding="utf-8"?>
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <!--
    Generated by init-environment.ps1
    Adjust paths to your local setup as needed.
  -->
  <PropertyGroup>
    <!-- Local path to game installation -->
    <ValheimPath>$detectedValheim</ValheimPath>

    <!-- Local path to r2modman profile (BepInEx) -->
    <R2ModmanProfileDir>$detectedR2</R2ModmanProfileDir>
  </PropertyGroup>
</Project>
"@

Set-Content -Path $targetProps -Value $xmlContent -Encoding UTF8
Write-Host "Successfully generated '$targetProps'!" -ForegroundColor Green

# 4. Check .gitignore
$gitignorePath = Join-Path $ProjectPath ".gitignore"
if (Test-Path $gitignorePath) {
    $gi = Get-Content $gitignorePath -Raw
    if ($gi -notmatch "(?m)^Environment\.props") {
        Add-Content -Path $gitignorePath -Value "`n# Local environment configuration`nEnvironment.props`n"
        Write-Host "Appended 'Environment.props' to .gitignore." -ForegroundColor Green
    }
}
